import { IMatch } from '../state/reducers/MatchesReducer'
import { IStreetPass } from '../state/reducers/StreetPassReducer'
import { InputLimits } from './constants'

const image1 = 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2023/04/20/16819946402834.jpg'
const image2 = 'https://www.lofficielbaltic.com/_next/image?url=https%3A%2F%2Fwww.datocms-assets.com%2F59774%2F1643351623-1571501184449345-captura-de-tela-2019-10-18-a-s-17-06-16.png%3Fauto%3Dformat%252Ccompress%26cs%3Dsrgb&w=3840&q=75'
const image3 = 'https://images.unsplash.com/photo-1524502397800-2eeaad7c3fe5?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGJlYXV0aWZ1bCUyMHdvbWFufGVufDB8fDB8fHww'

export const mockStreetPasses: Array<IStreetPass> = [
  {
    userId: '1',
    name: 'User one',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
  },
  {
    userId: '2',
    name: 'User two',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image2, },
      { image: image3, },
      { image: image1, },
    ],
  },
  {
    userId: '3',
    name: 'User three',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image3, },
      { image: image1, },
      { image: image2, },
    ],
  },
  {
    userId: '4',
    name: 'User four',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
  },
  {
    userId: '5',
    name: 'User five',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image2, },
      { image: image3, },
      { image: image1, },
    ],
  },
  {
    userId: '6',
    name: 'User six',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image3, },
      { image: image1, },
      { image: image2, },
    ],
  },
  {
    userId: '7',
    name: 'User seven',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    sex: false,
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
  },
]

export const mockMatches: Array<IMatch> = [
  {
    userId: '1',
    matchId: '1',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
    seen: false,
  },
  {
    userId: '1',
    matchId: '2',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image2, },
      { image: image3, },
      { image: image1, },
    ],
    seen: true,
  },
  {
    userId: '1',
    matchId: '3',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image3, },
      { image: image1, },
      { image: image2, },
    ],
    seen: true,
  },
  {
    userId: '1',
    matchId: '4',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
    seen: true,
  },
  {
    userId: '1',
    matchId: '5',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image2, },
      { image: image3, },
      { image: image1, },
    ],
    seen: true,
  },
  {
    userId: '1',
    matchId: '6',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image3, },
      { image: image1, },
      { image: image2, },
    ],
    seen: true,
  },
  {
    userId: '1',
    matchId: '7',
    name: 'User one',
    age: 19,
    sex: false,
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
    seen: true,
  },
]

export const mockChats = [
  {
    userId: '1',
    chatId: '1',
    name: 'User one',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: true,
  },
  {
    userId: '2',
    chatId: '2',
    name: 'User two',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image2, },
      { image: image3, },
      { image: image1, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: false,
  },
  {
    userId: '3',
    chatId: '3',
    name: 'User three',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image3, },
      { image: image1, },
      { image: image2, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: false,
  },
  {
    userId: '4',
    chatId: '4',
    name: 'User four',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: false,
  },
  {
    userId: '5',
    chatId: '5',
    name: 'User five',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image2, },
      { image: image3, },
      { image: image1, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: false,
  },
  {
    userId: '6',
    chatId: '6',
    name: 'User six',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image3, },
      { image: image1, },
      { image: image2, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: false,
  },
  {
    userId: '7',
    chatId: '7',
    name: 'User seven',
    bio: 'This is a bio',
    work: 'teacher',
    school: 'uvic',
    age: 19,
    date: new Date(),
    media: [
      { image: image1, },
      { image: image2, },
      { image: image3, },
    ],
    lastMessage: 'Lorem ipsum',
    updated: new Date(),
    unread: false,
  },
]

export const mockUserProfile = {
  userId: '1',
  phoneNumber: '',
  countryCode: '',
  email: '',
  name: 'User name',
  bio: 'User bio',
  age: 28,
  joinDate: new Date(),
  sex: true,
  media: [
    { image: image1, },
    { image: image2, },
    { image: image3, },
    { image: image1, },
    { image: image2, },
    { image: image3, },
    { image: image1, },
    { image: image2, },
  ],
  streetPass: true,
  streetPassPreferences: {
    discoverable: true,
    location: true,
    sex: null,
    age: [InputLimits.StreetPassAgeMin, InputLimits.StreetPassAgeMax],
  },
  notificationPreferences: {
    messages: true,
    matches: true,
    streetPasses: true,
    emails: true,
    newsletters: true,
  },
  privacyPreferences: {
    //
  },
}
